### ISSUE TITLE
Gigwa PB: Hangs when Investigate genotypes settings are used

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/PeanutbaseWebsite#15]
https://peanutbase.org/germplasm/gigwa

Peggy Ozias-Akins:
"We will soon have some additional data to send you to upload in peanutbase/gigwa.  I cannot get anything to output from the African Breeding Lines database even when I pare down the size of the search, although it worked very quickly with the Minicore database.  Could you check to see if there is a database issue?"

SD: 
As soon as I start using Investigate genoptype settings, even with US Minicore, it goes to perpetual search mode, "Finding matching variants ...". It doesn't even respond to Abort.

I think Gigwa is dockerized (?) and I don't have a way to look at any error messages.

**Comment by sdash-github** [comment]
**Andrew's comment**

Hi Sudhansu-
looks like gigwa is running as a tomcat application, not containerized. logs are here:
/usr/local/apache-tomcat-8.5/logs

here's the last message in the gigwa.log file:
22/02 09:31:12 | ERROR | http-nio-8080-exec-3 |fr.cirad.mgdb.service.GigwaGa4ghServiceImpl                  2650 | Error searching variants
java.lang.NullPointerException
        at fr.cirad.tools.mgdb.GenotypingDataQueryBuilder.next(GenotypingDataQueryBuilder.java:774)
        at fr.cirad.mgdb.service.GigwaGa4ghServiceImpl.findVariants(GigwaGa4ghServiceImpl.java:838)
        at fr.cirad.mgdb.service.GigwaGa4ghServiceImpl.searchVariants(GigwaGa4ghServiceImpl.java:2639)
        at fr.cirad.web.controller.ga4gh.Ga4ghRestController.searchVariants(Ga4ghRestController.java:519)
...


not sure how much that helps. I'll note that Sam is working on loading VCF into the mines, which could be an alternate path forward.

adf

**Comment by sammyjava** [comment]
The loading part is done. I've been playing with displayers. I'm using TestMine for that project.

https://dev.lis.ncgr.org/testmine/report.do?id=5000005

Be patient, the DataTables takes a while to load initially, but it pages pretty quickly. I'm looking at some fancier displays that have lots of tools.

I'm happy to load VCFs from the DS into PeanutMine, and just use the DataTables displayer until something better comes along.

**Comment by sdash-github** [comment]
**Location of data when ready to reload:**

- African lines (flapjack and hmp files):  https://legumeinfo.org/data/public/Arachis_hypogaea/arahy.gnm1.div.LZ50/  
  -- Modified to replace space in names #5

- US Minicore:  ?? (Haven't found the data yet)

**Comment by adf-ncgr** [comment]
as per the email I just sent, it doesn't appear that 
https://legumeinfo.org/data/public/Arachis_hypogaea/arahy.gnm1.div.LZ50/arahy.gnm1.div.LZ50.snp_chip.hmp.gz
is loading properly into gigwa (after uncompressing and renaming to have .hapmap extension). 
I think the file has no spaces in the names, but throwing this error
![image](https://user-images.githubusercontent.com/2009605/109058056-c44a1880-769f-11eb-9a1d-149de5e07da7.png)

may try reconverting to vcf before digging further into that error

**Comment by ekcannon** [comment]
There is mini core data here: https://v1.legumefederation.org/data/public/Arachis_hypogaea/aradu1_araip1.gnm1.div.2B6N/ Somewhere I have the file that I loaded way back when, probably on the machine in my office as I can't find it on the machine I'm using for teleworking.
